// <auto-generated />
using System;
using ArborFamiliae.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArborFamiliae.Data.Mysql.Migrations
{
    [DbContext(typeof(ArborFamiliaeContext))]
    partial class ArborFamiliaeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ArborFamiliae.Data.Models.Gender", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Gender");
                });

            modelBuilder.Entity("ArborFamiliae.Data.Models.Name", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Call")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FamiliyNickName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("NameTypeId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Suffix")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("NameTypeId");

                    b.HasIndex("PersonId");

                    b.ToTable("Name");
                });

            modelBuilder.Entity("ArborFamiliae.Data.Models.NameType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("NameType");
                });

            modelBuilder.Entity("ArborFamiliae.Data.Models.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ArborId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("GenderId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("PrimaryNameId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("Private")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("GenderId");

                    b.HasIndex("PrimaryNameId");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("ArborFamiliae.Data.Models.Surname", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Connector")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("NameId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Primary")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SurnameValue")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("NameId");

                    b.ToTable("Surname");
                });

            modelBuilder.Entity("ArborFamiliae.Data.Models.Name", b =>
                {
                    b.HasOne("ArborFamiliae.Data.Models.NameType", "NameType")
                        .WithMany()
                        .HasForeignKey("NameTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArborFamiliae.Data.Models.Person", null)
                        .WithMany("AlternateNames")
                        .HasForeignKey("PersonId");

                    b.Navigation("NameType");
                });

            modelBuilder.Entity("ArborFamiliae.Data.Models.Person", b =>
                {
                    b.HasOne("ArborFamiliae.Data.Models.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArborFamiliae.Data.Models.Name", "PrimaryName")
                        .WithMany()
                        .HasForeignKey("PrimaryNameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gender");

                    b.Navigation("PrimaryName");
                });

            modelBuilder.Entity("ArborFamiliae.Data.Models.Surname", b =>
                {
                    b.HasOne("ArborFamiliae.Data.Models.Name", "Name")
                        .WithMany("Surnames")
                        .HasForeignKey("NameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Name");
                });

            modelBuilder.Entity("ArborFamiliae.Data.Models.Name", b =>
                {
                    b.Navigation("Surnames");
                });

            modelBuilder.Entity("ArborFamiliae.Data.Models.Person", b =>
                {
                    b.Navigation("AlternateNames");
                });
#pragma warning restore 612, 618
        }
    }
}
